version: '3.1'

services:

  db:
    image: mariadb:10.3
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
