version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
